version: '3.8'

services:
  mongo:
    image: mongo:7
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    ports:
      - '8081:8081'
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/hypertube

  client:
    build: ./client
    ports:
      - '8080:80'
    depends_on:
      - server

volumes:
  mongo-data:
